# Generated by Django 4.2.7 on 2024-03-05 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='action',
            field=models.CharField(default=None, max_length=200, verbose_name='Действие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='Периодичность привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(default=None, max_length=200, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='Признак приятной привычки'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=None, verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
