# Generated by Django 4.2.7 on 2024-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_habit_action_habit_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта'),
        ),
    ]
