# Generated by Django 4.2.7 on 2024-03-11 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date_start',
            field=models.DateField(default=datetime.date(2024, 3, 12), verbose_name='Дата старта'),
        ),
    ]
